### PR TITLE
Get rid of dynamic properties to support PHP8.2

### PR DESCRIPTION
**Pull request by KminekMatej**
Property options has not been declared as class propery, simple declaration seem to suffice

### CODE REVIEW

**Comment by KminekMatej** [comment]
Afterwards I discovered another deprecation notice in snowflake generator (which has been already fixed in instaflake and sonyflake), so I fixed it as well in [13ea8ec] . Hope you dont mind I put it in the same PR, as its pretty much small

**Comment by KminekMatej** [comment]
@frodeborli could you please check and perhaps merge this PR, so I can cotinue using it on PHP8.2 server?

**Comment by frodeborli** [comment]
Thank you for the pull request, I merged it

**Comment by KminekMatej** [comment]
Thanks. Could you as well create new tag, so composer can autoinstall fixed version?

**Comment by frodeborli** [comment]
I will tag it, I just need to get to the PC, couldn't find a way to create a new tag via the the browser on github.com :)

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Matěj Kmínek ***@***.***>
Sendt: Wednesday, November 8, 2023 4:38:21 PM
Til: charm-php/uuid ***@***.***>
Kopi: Frode Børli ***@***.***>; Mention ***@***.***>
Emne: Re: [charm-php/uuid] Get rid of dynamic properties to support PHP8.2 (PR #1)


Thanks. Could you as well create new tag, so composer can autoinstall fixed version?

**Comment by KminekMatej** [comment]
Odd, I dont see these changes in latest tag, nor in Main. And here it looks like not merged. Did you really merge it? (I ran to the same problem again, after composer update)

**Comment by KminekMatej** [comment]
I created new pull request https://github.com/charm-php/uuid/pull/2 - could you check / merge / tag that again? (absolutely same changes)

**Pull request closed without merging**
